{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sill.fullname" . }}
  labels:
    app: {{ template "sill.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.api.env }}
{{- range $key, $value := .Values.api.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end -}}
{{- end -}}
{{- if .Values.api.regions }}
  regions: {{ .Values.api.regions | toJson | b64enc | quote }}
{{- end}}
{{- if .Values.api.catalogs }}
  catalogs: {{ .Values.api.catalogs | toJson | b64enc | quote }}
{{- end}}
{{- end}}
