# build step
FROM node:20-alpine as build
WORKDIR /app
COPY package.json yarn.lock ./
COPY api/package.json api/
COPY api/.env.sh api/
COPY web/package.json web/
COPY web/public/ web/public/

RUN yarn install --frozen-lockfile

COPY turbo.json ./
COPY api/ api/
COPY web/src/ web/src/
COPY web/config-overrides.js web/tsconfig.json web/

WORKDIR /app
RUN yarn build

WORKDIR /app
COPY web/nginx.conf web/

## ----- web only ------
# to build only front run
# docker build . --target web --tag my-web-tag
FROM nginx:stable-alpine as web
COPY --from=build /app/web/nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx
COPY --from=build /app/web/build ./html
ENTRYPOINT sh -c "nginx -g 'daemon off;'"
