# SPDX-FileCopyrightText: 2021-2025 DINUM <floss@numerique.gouv.fr>
# SPDX-FileCopyrightText: 2024-2025 Université Grenoble Alpes
# SPDX-License-Identifier: MIT

# build step
FROM node:22-alpine as build
WORKDIR /app
COPY package.json yarn.lock ./
COPY api/package.json api/
COPY web/package.json web/
COPY web/public/ web/public/
COPY web/index.html web/

RUN yarn install --frozen-lockfile

COPY turbo.json ./
COPY api/ api/
COPY web/src/ web/src/
COPY web/vite.config.ts web/tsconfig.json web/.env.declaration web/

WORKDIR /app
RUN yarn build

WORKDIR /app
COPY web/nginx.conf web/

## ----- web only ------
# to build only front run
# docker build . --target web --tag my-web-tag
FROM nginx:stable-alpine as web
RUN apk add --update nodejs npm
COPY --from=build /app/web/nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx
COPY --from=build /app/web/build ./html
RUN npm i -g vite-envs@`node -e 'console.log(require("./.vite-envs.json").version)'`
ENTRYPOINT sh -c "npx vite-envs && nginx -g 'daemon off;'"

