# build step
FROM node:20-alpine as build
WORKDIR /app
COPY package.json yarn.lock ./
COPY api/package.json api/
COPY web/package.json web/
COPY web/public/ web/public/
COPY web/index.html web/

RUN yarn install --frozen-lockfile

COPY turbo.json ./
COPY api/ api/
COPY web/src/ web/src/
COPY web/vite.config.ts web/tsconfig.json web/

WORKDIR /app
RUN yarn build

WORKDIR /app
COPY web/nginx.conf web/


FROM nginx:stable-alpine as web
COPY --from=build /app/web/nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx
COPY --from=build /app/web/build ./html
ENTRYPOINT sh -c "nginx -g 'daemon off;'"
